package com.example.MyBookShopApp.data;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import javax.persistence.*;
import java.util.ArrayList;
import java.util.List;

@Entity
@Table(name = "tags")
@ApiModel(description = "entity representing a tags")
public class Tag {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @ApiModelProperty("id generated by db automaticaly")
    private Integer id;

    @Column(name="tags")
    @ApiModelProperty("mnemonical identity sequence of characters")
    private String name;

    @OneToMany
    @JoinTable (name="books2tags",
            joinColumns = @JoinColumn (name = "tag_id"),
            inverseJoinColumns = @JoinColumn(name="book_id"))
    private List<Book> booksListOfTag;


    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public List<Book> getBooksListOfTag() {
        return booksListOfTag;
    }

    public void setBooksListOfTag(List<Book> booksListOfTag) {
        this.booksListOfTag = booksListOfTag;
    }
}
