insert into authors (id, first_name, last_name) values (1, 'Delbert', 'McFeat');
insert into authors (id, first_name, last_name) values (2, 'Seth', 'Scoon');
insert into authors (id, first_name, last_name) values (3, 'Adamo', 'Stratiff');
insert into authors (id, first_name, last_name) values (4, 'Jeana', 'Cuffley');
insert into authors (id, first_name, last_name) values (5, 'Cart', 'Stean');
insert into authors (id, first_name, last_name) values (6, 'Min', 'Moggie');
insert into authors (id, first_name, last_name) values (7, 'Dolf', 'Cawsey');
insert into authors (id, first_name, last_name) values (8, 'Joye', 'Motte');
insert into authors (id, first_name, last_name) values (9, 'Scott', 'Sember');
insert into authors (id, first_name, last_name) values (10, 'Simonne', 'Risbie');
insert into authors (id, first_name, last_name) values (11, 'Hobie', 'Kenewel');
insert into authors (id, first_name, last_name) values (12, 'Caritta', 'Lequeux');
insert into authors (id, first_name, last_name) values (13, 'Merilyn', 'Dillinton');
insert into authors (id, first_name, last_name) values (14, 'Herby', 'Culp');
insert into authors (id, first_name, last_name) values (15, 'Lottie', 'Pendre');
insert into authors (id, first_name, last_name) values (16, 'Petey', 'Caudell');
insert into authors (id, first_name, last_name) values (17, 'Leontyne', 'Teece');
insert into authors (id, first_name, last_name) values (18, 'Reta', 'Fawlkes');
insert into authors (id, first_name, last_name) values (19, 'Marchall', 'Goodenough');
insert into authors (id, first_name, last_name) values (20, 'Fleming', 'Megarrell');
insert into authors (id, first_name, last_name) values (21, 'Odele', 'Chiese');
--
insert into books (id, price, price_old, title, author_id) values (1, 507, 426, 'Fix San', 20);
insert into books (id, price, price_old, title, author_id) values (2, 956, 413, 'Job', 5);
insert into books (id, price, price_old, title, author_id) values (3, 982, 463, 'Asoka', 6);
insert into books (id, price, price_old, title, author_id) values (4, 915, 330, 'Stim', 8);
insert into books (id, price, price_old, title, author_id) values (5, 710, 685, 'Konklux', 9);
insert into books (id, price, price_old, title, author_id) values (6, 638, 618, 'Alpha', 1);
insert into books (id, price, price_old, title, author_id) values (7, 527, 449, 'Bamity', 4);
insert into books (id, price, price_old, title, author_id) values (8, 513, 347, 'Namfix', 5);
insert into books (id, price, price_old, title, author_id) values (9, 819, 440, 'Home Ing', 8);
insert into books (id, price, price_old, title, author_id) values (10, 849, 321, 'Regrant', 19);
insert into books (id, price, price_old, title, author_id) values (11, 570, 722, 'Subin', 16);
insert into books (id, price, price_old, title, author_id) values (12, 876, 491, 'Stringtough', 12);
insert into books (id, price, price_old, title, author_id) values (13, 614, 409, 'Duobam', 19);
insert into books (id, price, price_old, title, author_id) values (14, 908, 317, 'Latlux', 20);
insert into books (id, price, price_old, title, author_id) values (15, 651, 515, 'Latlux', 20);
insert into books (id, price, price_old, title, author_id) values (16, 775, 547, 'Aerified', 4);
insert into books (id, price, price_old, title, author_id) values (17, 667, 610, 'Vagram', 14);
insert into books (id, price, price_old, title, author_id) values (18, 581, 719, 'Viva', 21);
insert into books (id, price, price_old, title, author_id) values (19, 501, 714, 'Bitchip', 20);
insert into books (id, price, price_old, title, author_id) values (20, 981, 415, 'Treeflex', 21);
insert into books (id, price, price_old, title, author_id) values (21, 786, 669, 'Zamit', 15);
